String response001 = ""
"<!DOCTYPE html>"
"<html>"
"<head>"
"<title>Virus Distribution Point</title>"
"</head>"
"<style type=\"text/css\">"
"body {background-color: #000; color: #FFF;}"
"#titlehead {color: #F00;}"
"#actionhead,#attackvectors,#exploiting,#installing {visibility: hidden;}"
".ver {color: white;}"
".inline {display: inline;}"
"#offline {color: green;}"
"#disarmed {color: green;}"
"</style>"
"<body>"
"<h1>"
"<div id=\"titlehead\">"
"Virus Distribution Point"
"</div>"
"</h1>"
"<div id=\"status\">"
"<p>"
"<div class=\"inline\">Version:</div>"
"<div id=\"ver0\" class=\"ver inline\">99</div>."
"<div id=\"ver1\" class=\"ver inline\">99</div>."
"<div id=\"ver2\" class=\"ver inline\">99</div>"
"</p>"
"<p>"
"<div class=\"inline\">Status:</div> "
"<div id=\"offline\" class=\"inline\">offline</div> / <div id=\"disarmed\" class=\"inline\">disarmed</div></p>"
"</div>"
"<p>"
"<div id=\"actionhead\">"
"Scanning your computer"
"</div>"
"</p>"
"<p>"
"<div id=\"attackvectors\">"
"Found potential security holes in your system: <div id=\"attacknum\" class=\"inline\">0</div>"
"</div>"
"</p>"
"<p>"
"<div id=\"exploiting\">"
"Exploiting vulnerabilities: <div id=\"exploitnum\" class=\"inline\"></div>"
"</div>"
"<div id=\"exploits\">"
"</div>"
"</p>"
"<p>"
"<div id=\"installing\">"
"Installing viruses: <div id=\"installnum\" class=\"inline\"></div>"
"</div>"
"</p>"
"<script>"
"var decTimer = setInterval(decCounter, 30);"
"var statusTimer = setTimeout(statusTrigger, 3000);"
"var actionTimer;"
"var actionCount = 0;"
"var attackTimer;"
"var attackCount = 0;"
"var exploitTimer;"
"var exploitCount = 0;"
"var exploitLast;"
"var installingTimer;"
"var installingCount = 0;"
"var colorTimer;"
"var colorIndex = 0;"
"var titleText = document.getElementById(\"titlehead\").innerHTML;"
""
"function onload(){"
"}"
""
"function marqueeBounce(){"
"    var tmarq = document.getElementById(\"titlemarquee\");"
"    if(marqdir == \"down\")"
"        tmarq.direction = \"up\";"
"    else"
"        tmarq.direction = \"down\";"
"}"
""
"function decCounter(){"
"    var ver0 = document.getElementById(\"ver0\");"
"    var ver1 = document.getElementById(\"ver1\");"
"    var ver2 = document.getElementById(\"ver2\");"
"    var val0 = ver0.innerHTML;"
"    if(val0 > 6){"
"        val0 -= 1;        "
"        ver0.innerHTML = val0;"
"    }else{"
"        ver0.style = \"color:red; font-weight:bold;\";"
"    }    "
"    if(val0 > 50){"
"        return;"
"    }"
"    var val1 = ver1.innerHTML;"
"    if(val1 > 6){"
"        val1 -= 1;"
"        ver1.innerHTML = val1;"
"    }else{"
"        ver1.style = \"color:red; font-weight:bold;\";"
"    }    "
"    if(val1 > 50){"
"        return;"
"    }"
"    var val2 = ver2.innerHTML;"
"    if(val2 > 6){"
"        val2 -= 1;"
"        ver2.innerHTML = val2;"
"    }else{"
"        ver2.style = \"color:red; font-weight:bold;\";"
"        clearInterval(decTimer);        "
"    }"
"}"
""
"function statusTrigger(){"
"    var offline = document.getElementById(\"offline\");"
"    if(offline.innerHTML == \"offline\"){"
"        offline.innerHTML = \"ONLINE\";"
"        offline.style = \"color:blue; font-weight:bold;\";"
"        statusTimer = setTimeout(statusTrigger, 2000);"
"        return;"
"    }"
"    var disarmed = document.getElementById(\"disarmed\");"
"    if(disarmed.innerHTML == \"disarmed\"){"
"        disarmed.innerHTML = \"ARMED\";"
"        disarmed.style = \"color:yellow; font-weight:bold;\";"
"        statusTimer = setTimeout(statusTrigger, 1500);"
"        return;"
"    }"
"    "
"    "
"    actionTrigger();"
"    "
"}"
""
"function actionTrigger(){"
"    var actionhead = document.getElementById(\"actionhead\");"
"    if(actionTimer == null){        "
"        actionhead.style = \"visibility: visible;\";"
"        actionTimer = setInterval(actionTrigger, 100);  "
"        return; "
"    }"
"    if(actionCount < 30){"
"        actionCount += 1;"
"        actionhead.innerHTML += \".\";"
"        return;"
"    }"
"    "
"    clearInterval(actionTimer);"
"    "
"    "
"    attackTrigger();"
"}"
""
"function attackTrigger(){"
"    var attackvectors = document.getElementById(\"attackvectors\");"
"    if(attackTimer == null){"
"        attackvectors.style = \"visibility: visible;\";"
"        attackTimer = setInterval(attackTrigger, 100);  "
"        return; "
"    }"
"    if(attackCount < 42){"
"        var attacknum = document.getElementById(\"attacknum\");"
"        attackCount += 1;"
"        attacknum.innerHTML = attackCount;"
"        return;"
"    }"
"    "
"    clearInterval(attackTimer);"
"    "
"    "
"    exploitTrigger();    "
"}"
""
"var exploitStrings = ["
"    \"hacking dns routing\","
"    \"brute force password bypass\","
"    \"forcing buffer overrun by injecting null\","
"    \"secondary cache lookup injection\","
"    \"weak firewall rules fusing\","
"    \"php server side constriction hack\","
"    \"devolving integer rollover\""
"];"
""
"function exploitTrigger(){"
"    var exploiting = document.getElementById(\"exploiting\");"
"    if(exploitTimer == null){"
"        exploiting.style = \"visibility: visible;\";"
"        exploitTimer = setInterval(exploitTrigger, 100);  "
"        return; "
"    }"
"    if(exploitCount < 42){"
"        var exploits = document.getElementById(\"exploits\");"
"        var exploitnum = document.getElementById(\"exploitnum\");"
"        exploitCount += 1;"
"        exploitnum.innerHTML = exploitCount;"
"        var eindex = exploitCount/6 - 1;"
"        if(exploitCount % 6 == 0){"
"            if(exploitCount != 42){"
"                exploits.innerHTML += '<div class=\"inline\" style=\"color: green;\">' + exploitStrings[eindex] + '...failed</div>' + \"<br/>\";            "
"            }else{"
"                exploits.innerHTML += '<div class=\"inline\" style=\"color: yellow;\">' + exploitStrings[eindex] + '...success!</div>' + \"<br/>\";"
"            }            "
"        }"
"        return;"
"    }"
" "
"    clearInterval(exploitTimer);"
"    "
"    "
"    installTrigger();"
"}"
""
"function installTrigger(){"
"    var installing = document.getElementById(\"installing\");"
"    if(installingTimer == null){"
"        installing.style = \"visibility: visible;\";"
"        installingTimer = setInterval(installTrigger, 100);  "
"        return; "
"    }"
"    var installnum = document.getElementById(\"installnum\");"
"    var installmax = 97;"
"    if(installingCount < 97){        "
"        installingCount += 1;"
"        installnum.innerHTML = installingCount + \"/\" + installmax;"
"        return;"
"    }"
"    "
"    installnum.innerHTML = \"100% Complete\";"
"    "
"    clearInterval(installingTimer);"
"    "
"    "
"    colorTitle();"
"}"
""
"var titleColors = ["
"    \"red\","
"    \"green\","
"    \"blue\","
"    \"yellow\","
"    \"cyan\","
"    \"purple\""
"];"
""
"function colorTitle(){"
"    var titlehead = document.getElementById(\"titlehead\");"
"    if(colorTimer == null){"
"        colorTimer = setInterval(colorTitle, 100);  "
"        return;"
"    }"
"        "
"    colorIndex += 1;"
"    var colorMax = titleColors.length;"
"    if(colorIndex >= colorMax){"
"        colorIndex = 0;        "
"    }"
"        "
"    var titleArray = titleText.split(\"\");"
"    var outString = \"\";"
"    var chrCount = 0;"
"    var chr;"
"    for(ch in titleArray){"
"        outString += '<div class=\"inline\" style=\"color:' + titleColors[(chrCount+colorIndex)%colorMax] + '\">'+titleArray[ch]+'</div>';"
"        "
"        chrCount += 1;"
"    }"
"    titlehead.innerHTML = outString;"
"}"
""
""
"</script>"
"</body>"
"</html>"
;
